### ISSUE TITLE
SearchGraph appears broken

### ISSUE THREAD

**Issue by nlw0** [sadit/SimilaritySearch.jl#28]
Hi, I've been using a few functions from this package, just tried out something new (`SearchGraph`), and it seems broken to me. Am I doing something wrong? I'm trying to reproduce the example in https://sadit.github.io/SimilaritySearchDemos/demos/

```
julia> using SimilaritySearch

julia> db = MatrixDatabase(randn(Float32, 2, 10^3))
MatrixDatabase{Matrix{Float32}}(Float32[-1.1481045 0.41961858 … 1.1541021 -0.5108408; -0.63705605 -1.7388542 … -1.3868691 0.08434687])

julia> Q = MatrixDatabase(randn(Float32, 2, 30))
MatrixDatabase{Matrix{Float32}}(Float32[0.03854982 0.3528542 … -0.67747146 1.2158719; -0.75761163 -0.85801506 … -0.023984894 0.18272546])

julia> G = SearchGraph(dist=SqL2Distance(), db=db, verbose=true)
SearchGraph{SqL2Distance, MatrixDatabase{Matrix{Float32}}, SimilaritySearch.AdjacencyLists.AdjacencyList{UInt32}, BeamSearch}
  dist: SqL2Distance SqL2Distance()
  db: MatrixDatabase{Matrix{Float32}}
  adj: SimilaritySearch.AdjacencyLists.AdjacencyList{UInt32}
  hints: Array{Int32}((0,)) Int32[]
  search_algo: BeamSearch
  len: Base.RefValue{Int64}
  verbose: Bool true


julia> # G = ExhaustiveSearch(SqL2Distance(), db)
       I, D = searchbatch(G,Q,10)
(Int32[0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0], Float32[1.0f-45 3.0f-45 … -1.4247362f-37 1.1941433; 0.0 0.0 … 4.5717f-41 4.5717f-41; … ; 3.0f-45 1.0f-45 … -1.4391214f-37 0.0; 0.0 0.0 … 4.5717f-41 0.0])

julia> search(G, Q[2], KnnResult(2))
(res = KnnResult(Int32[], Float32[], 2), cost = 0)

```

Although it runs without errors, it seems nothing can be found. It all seems fine with `ExhaustiveSearch`, though. Am I missing some parameter when building the graph, perhaps?

**Comment by sadit** [comment]
Oh, the API used in demos has some minor changes, but some are breaking.

In the new version you need to call `index!` after defining `G` or define `db` as an empty database (using `VectorDatabase` or `DynamicMatrixDatabase`) and then use `push_item!` or `append_items!`.

In <https://github.com/sadit/SimilaritySearch.jl/blob/aebe1ff6751df1c089ddfd8acab74c6ba86691e7/test/testsearchgraph.jl#L78>

You can see a working example.

If this works, can you please close this issue and open a new one about updating examples?

**Comment by sadit** [comment]
@nlw0 just updated examples and demos at https://sadit.github.io/SimilaritySearchDemos/ most of them should work now (only Pluto notebooks were left in the previous API)
