### ISSUE TITLE
have some benchmark ? 

### ISSUE THREAD

**Issue by zsz00** [sadit/SimilaritySearch.jl#9]
I use cosine distance , search ,  same vector cos  is 0.93, not 1.0. 

is there have some benchmark  of accuracy and speed???

**Comment by sadit** [comment]
Hi, the benchmark comes in the paper. In general, you may want to try to match your dataset's characteristics with one of the presented benchmarks to try to figure out how it will perform.

_Tellez, E. S., Ruiz, G., Chavez, E., & Graff, M.A scalable solution to the nearest neighbor search problem through local-search methods on neighbor graphs. Pattern Analysis and Applications, 1-15._

I assume that you are using the SearchGraph index. The performance will be linked with the entire collection and parameters used for the index construction. Perhaps if you give me more information I can figure out if it is the expected performance or there is a bug somewhere.

**Comment by sadit** [comment]
The indexes in the package use dissimilarities (or distances) instead of similarities, then CosineDistance computes `1 - cos(.)`.

I think that the results are correct/expected (small negative distances are due to floating-point arithmetic)

```julia
julia> evaluate(CosineDistance(), feats[1], feats[1])
-1.1920929f-7

julia> evaluate(CosineDistance(), feats[2], feats[2])
0.0f0

julia> evaluate(CosineDistance(), feats[1], feats[2])
0.20484513f0
```

**Comment by zsz00** [comment]
ok, i see, thank you very much...
